### ISSUE TITLE
--delete-access-point-root-dir=true might delete wrong dir

### ISSUE THREAD

**Issue by MiGrandjean** [kubernetes-sigs/aws-efs-csi-driver#1085]
/kind bug

**What happened?**

We deployed aws-efs-csi-driver with `--delete-access-point-root-dir=true`. At some point all contents of the EFS filesystem got deleted. No `/pvc-....` folders were left. The monitoring looks like this:

![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/8418423/f36dc544-d132-41d3-b659-dd668ba3d052)

Note the drop of storage bytes at 16:30. 

**What you expected to happen?**

Don't delete all EFS AccessPoints/RootDirs.

**How to reproduce it (as minimally and precisely as possible)?**

I'm still trying to reproduce this behavior. Any hints what might have caused this are appreciated.

**Anything else we need to know?**:

According to the logs, aws-efs-csi-driver tried to delete an existing PVC `pvc-957369e3-1128-4e25-a6d5-e6b1e7a6299a` minutes before the incident, but failed at first:

```
{"log":"I0726 16:25:04.800727       1 controller.go:1471] delete \"pvc-957369e3-1128-4e25-a6d5-e6b1e7a6299a\": started\n","stream":"stderr","time":"2023-07-26T16:25:04.800967025Z"}
{"log":"I0726 16:25:04.800792       1 controller.go:1279] volume pvc-957369e3-1128-4e25-a6d5-e6b1e7a6299a does not need any deletion secrets\n","stream":"stderr","time":"2023-07-26T16:25:04.801012807Z"}
{"log":"W0726 16:25:14.801335       1 controller.go:989] Retrying syncing volume \"pvc-957369e3-1128-4e25-a6d5-e6b1e7a6299a\", failure 514\n","stream":"stderr","time":"2023-07-26T16:25:14.801483546Z"}
{"log":"E0726 16:25:14.801598       1 controller.go:1007] error syncing volume \"pvc-957369e3-1128-4e25-a6d5-e6b1e7a6299a\": rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2023-07-26T16:25:14.802019594Z"}
{"log":"I0726 16:25:14.801625       1 event.go:285] Event(v1.ObjectReference{Kind:\"PersistentVolume\", Namespace:\"\", Name:\"pvc-957369e3-1128-4e25-a6d5-e6b1e7a6299a\", UID:\"ccc26272-7ea2-4ab9-beb0-e1445e8cea1f\", APIVersion:\"v1\", ResourceVersion:\"41843626\", FieldPath:\"\"}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2023-07-26T16:25:14.802030534Z"}
```

The logs stop after that. Five minutes later, the EFS filesystem is empty.

I also found a mount error in the logs some hours earlier for the corresponding Access Point:

```
{"log":"E0725 09:46:14.712594       1 driver.go:103] GRPC error: rpc error: code = Internal desc = Could not mount \"fs-0188ca211fd8cc57a\" at \"/var/lib/csi/pv/fsap-0e4937bb9f159e1ec\": mount failed: exit status 32\n","stream":"stderr","time":"2023-07-26T09:46:14.712724126Z"}
```

AFAICS "Could not mount ..." is the error message in the `DeleteVolume` [function in controller.go](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.5.5/pkg/driver/controller.go#L278) if the mount fails during the "//Mount File System at it root and delete access point root directory"-logic.
Is it possible that prior to this, not `/pvc-957369e3-1128-4e25-a6d5-e6b1e7a6299a` got deleted, but `/`? E.g. can `AccessPointRootDir` be empty, or sth similar?

16:30 UTC is outside of our core working hours and aws-efs-csi-driver is the only tool that operates with delete permissions on the EFS filesystem. 

**Environment**
- Kubernetes version (use `kubectl version`): Server Version: v1.23.17-eks-a5565ad
- Driver version: v1.5.5

**Please also attach debug logs to help us better diagnose**

TBD

**Comment by MiGrandjean** [comment]
I was able to reproduce the behaviour with enabled debug logs and attached the results of the logcollector [as described here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting): 

[results.zip](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/12251698/results.zip)

## What I did this time:

1. I deployed `aws-efs-csi-driver` via the Helm Chart (2.4.3) with these additional values:

```yaml
controller:
  deleteAccessPointRootDir: true
  logLevel: 5
node:
  logLevel: 5
```

2. I enabled stunnel debug in the efs-plugin container on my 1 node

```
sed -i '/stunnel_debug_enabled = false/s//stunnel_debug_enabled = true/g' /etc/amazon/efs/efs-utils.conf
sed -i '/logging_level = INFO/s//logging_level = DEBUG/g' /etc/amazon/efs/efs-utils.conf
```

3.  I added some dummy files to the EFS filesystem (using `dd`) at the top level:

```
[root@ip-10-1-129-238 ~]# ls -ltr /mnt/efs/
drwx------ 3 rngd input      6144 Aug  2 14:01 pvc-a8f802cb-2bf8-452b-a06d-0835781472eb
drwx------ 3 rngd input      6144 Aug  2 14:27 pvc-a83e4189-5b6d-43b1-855e-c57807220d02
-rw-r--r-- 1 root root  536870912 Aug  3 10:15 dummy_file
-rw-r--r-- 1 root root  536870912 Aug  3 10:16 dummy_file2
-rw-r--r-- 1 root root  536870912 Aug  3 10:16 dummy_file3
drwxr-xr-x 2 root root       6144 Aug  3 10:18 manual_dir
```

4. I then deployed 10 instances of our application that uses one PVC per instance. The EFS then looked like this:

```
[root@ip-10-1-129-238 ~]# ls -ltr /mnt/efs/
total 64
drwx------ 3 rngd input      6144 Aug  2 14:01 pvc-a8f802cb-2bf8-452b-a06d-0835781472eb
drwx------ 3 rngd input      6144 Aug  2 14:27 pvc-a83e4189-5b6d-43b1-855e-c57807220d02
-rw-r--r-- 1 root root  536870912 Aug  3 10:15 dummy_file
-rw-r--r-- 1 root root  536870912 Aug  3 10:16 dummy_file2
-rw-r--r-- 1 root root  536870912 Aug  3 10:16 dummy_file3
drwxr-xr-x 2 root root       6144 Aug  3 10:18 manual_dir
drwx------ 3 rngd input      6144 Aug  3 11:45 pvc-5496e45b-7e0c-4e1d-8cfe-22d2d91ec010
drwx------ 3 rngd input      6144 Aug  3 11:45 pvc-31b88ebb-aada-4fc5-9664-0528f188c12a
drwx------ 3 rngd input      6144 Aug  3 11:45 pvc-17b576c3-fb57-4227-bbd6-896a74831c3c
drwx------ 3 rngd input      6144 Aug  3 11:45 pvc-5584947b-06be-49af-9041-aa52a576d1fd
drwx------ 3 rngd input      6144 Aug  3 11:45 pvc-2add4d54-2f81-4c79-8b74-04572d7956e6
drwx------ 3 rngd input      6144 Aug  3 11:45 pvc-69ab4ca4-65b4-4902-9b97-9f7a9a3f3e3a
drwx------ 3 rngd input      6144 Aug  3 11:46 pvc-b8f70134-aed2-4e47-bde4-0736c2b9854f
drwx------ 3 rngd input      6144 Aug  3 11:46 pvc-9a5abe17-bf4c-4407-aee3-36c168f52269
drwx------ 3 rngd input      6144 Aug  3 11:46 pvc-061e2c50-1561-4be5-9932-6267fc84760e
drwx------ 3 rngd input      6144 Aug  3 11:46 pvc-1293730a-a206-426a-b396-8619b43c1c58
```

5. After the deployment was successful, I _uninstalled_ all 10 instances. After a few minutes, the EFS was **empty**. Even the manually added files were gone:

```
[root@ip-10-1-129-238 ~]# ls -lah /mnt/efs/
total 4.0K
drwxr-xr-x 2 root root 6.0K Aug  3 12:25 .
drwxr-xr-x 3 root root   17 Aug  3 10:13 ..
```

This is our Grafana dashboard with EFS Storage Bytes:

![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/8418423/4081d3e1-bf0a-4daa-8409-7f17961bf479)

(please note: The timestamps above are UTC, the ones in the Grafana screenshot are UTC+2)

6. We collect Container logs with Promtail/Loki and I can see these logs coming from the `csi-provisioner` Container

What I can see in the Loki logs is that it starts to delete the PVC folders and then fails after 10s with `volume deletion failed: rpc error: code = DeadlineExceeded`

```
{"log":"I0803 12:24:35.819681       1 controller.go:1471] delete \"pvc-5584947b-06be-49af-9041-aa52a576d1fd\": started\n","stream":"stderr","time":"2023-08-03T12:24:35.819838196Z"}
{"log":"I0803 12:24:36.533382       1 controller.go:1471] delete \"pvc-2add4d54-2f81-4c79-8b74-04572d7956e6\": started\n","stream":"stderr","time":"2023-08-03T12:24:36.533543967Z"}
{"log":"I0803 12:24:36.826410       1 controller.go:1471] delete \"pvc-b8f70134-aed2-4e47-bde4-0736c2b9854f\": started\n","stream":"stderr","time":"2023-08-03T12:24:36.833902331Z"}
{"log":"E0803 12:24:45.820805       1 controller.go:1481] delete \"pvc-5584947b-06be-49af-9041-aa52a576d1fd\": volume deletion failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2023-08-03T12:24:45.820941694Z"}
{"log":"E0803 12:24:46.534689       1 controller.go:1481] delete \"pvc-2add4d54-2f81-4c79-8b74-04572d7956e6\": volume deletion failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2023-08-03T12:24:46.53484165Z"}
{"log":"I0803 12:24:46.821598       1 controller.go:1471] delete \"pvc-5584947b-06be-49af-9041-aa52a576d1fd\": started\n","stream":"stderr","time":"2023-08-03T12:24:46.821876582Z"}
{"log":"E0803 12:24:46.834916       1 controller.go:1481] delete \"pvc-b8f70134-aed2-4e47-bde4-0736c2b9854f\": volume deletion failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2023-08-03T12:24:46.834982286Z"}
{"log":"I0803 12:24:47.535599       1 controller.go:1471] delete \"pvc-2add4d54-2f81-4c79-8b74-04572d7956e6\": started\n","stream":"stderr","time":"2023-08-03T12:24:47.535778358Z"}
{"log":"I0803 12:24:47.835858       1 controller.go:1471] delete \"pvc-b8f70134-aed2-4e47-bde4-0736c2b9854f\": started\n","stream":"stderr","time":"2023-08-03T12:24:47.836008165Z"}
{"log":"E0803 12:24:54.879658       1 driver.go:103] GRPC error: rpc error: code = Internal desc = Failed to Delete volume fs-0f4f885c773bf17d5::fsap-0c4ed3cd16c584676: Failed to delete access point: fsap-0c4ed3cd16c584676, error: RequestCanceled: request context canceled\n","stream":"stderr","time":"2023-08-03T12:24:54.880908443Z"}
2023-08-03T14:24:56+02:00	{"log":"E0803 12:24:56.240292       1 driver.go:103] GRPC error: rpc error: code = Internal desc = Failed to Delete volume fs-0f4f885c773bf17d5::fsap-0aff425573c27b118: Failed to delete access point: fsap-0aff425573c27b118, error: RequestCanceled: request context canceled\n","stream":"stderr","time":"2023-08-03T12:24:56.240412084Z"}
{"log":"E0803 12:24:56.220653       1 controller.go:1481] delete \"pvc-b8f70134-aed2-4e47-bde4-0736c2b9854f\": volume deletion failed: rpc error: code = Internal desc = Could not unmount \"/var/lib/csi/pv/fsap-0aff425573c27b118\": unmount failed: exit status 32\n","stream":"stderr","time":"2023-08-03T12:24:56.220689937Z"}
{"log":"E0803 12:24:56.822007       1 controller.go:1481] delete \"pvc-5584947b-06be-49af-9041-aa52a576d1fd\": volume deletion failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2023-08-03T12:24:56.822143818Z"}
{"log":"E0803 12:24:57.535838       1 controller.go:1481] delete \"pvc-2add4d54-2f81-4c79-8b74-04572d7956e6\": volume deletion failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2023-08-03T12:24:57.536657442Z"}
```

7. Another obersvation: Although the EFS filesystem is *empty*, AWS still shows the AccessPoints:

![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/8418423/760357e7-ab1b-4ea4-9950-c0a47295fbef)

**Comment by RyanStan** [comment]
Thanks for bringing this to our attention. We'll investigate this immediately.

**Comment by RyanStan** [comment]
Using the latest Helm Chart release with out v1.5.5 image, I haven't been able to recreate this issue. 

Could you try reproducing the issue with application Pods that don't run your workload? For example, an Amazon Linux image with no arguments. This will help us figure out whether it's the workload that is deleting the files.

If we're unable to reproduce the issue, then I recommend opening a technical support case with AWS. That will allow us to have a private channel to investigate further.

**Comment by makomatic** [comment]
> Could you try reproducing the issue with application Pods that don't run your workload? For example, an Amazon Linux image with no arguments.

I know that I won't convince you by just telling - but I ensure you that it's not the workload. We're running this for years for many many customers in very big production environments. This never happened and I am damn sure that the application does not delete its root ;-)

We deviced to not make use of this feature anymore and clean up by hand - which is kinda disturbing, but - to be honest with you - we plan to change the storage provider anyway and we will not reproduce it again in our environment.
We also can't open another case with AWS (we had one when it happened) because we currently have no problem.

Anyway thx for checking it out.

**Comment by mskanth972** [comment]
Thank you for reporting this issue to us. Our team has diligently tried to recreate the scenario as you described, but we have not been successful in replicating the problem in our own environment. Additionally, after reviewing the code, it appears that the deletion process should not result in the removal of all contents. Given that we cannot reproduce the issue, our ability to provide further assistance is restricted. Therefore, we will be closing this issue at this time.

**Comment by EinavDanielDX** [comment]
We are having a similat issue in our testing cluster. its most frustrating as its not consistent.
In our environment there are constant E2E tests, creating and deleting namespaces and workloads.
Every once in a while the deletion of a namespace and it's resources (always gracefully) results in data termination of all of the files in EFS, even though the access points are not deleted. 

In this screenshot you can see it happened 3 times in that last week, data is restored manually each time.
![image](https://github.com/user-attachments/assets/cca80f21-932e-4941-8f9b-5c20303f00b7)

**Comment by 617m4rc** [comment]
We've recently hit this issue in one of our production clusters and with EFS CSI driver version v2.0.5. The reproduction steps are exactly as described above. I am surprised that such a massive issue is being ignored. From my point of view, an immediate fix is imperative.

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/a24f7be9-ad4e-433c-b42b-2a9ea6b285c9">

**Comment by mskanth972** [comment]
Closing this issue as we released a Fix in the latest versions.

**Comment by Phaow** [comment]
Hi @mskanth972 @dankova22 , with the root cause analyze -> https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1085#issuecomment-2532364778  I tried to reproduce the issue follow steps
```console
# Reproducer steps

# STEP1: create storageclass with basePath: "/" and 2 pvc with pods
$ oc apply -f - <<EOF
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-root
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-04a5e85869452b2fa
  directoryPerms: "700"
  basePath: "/"
EOF
storageclass.storage.k8s.io/efs-sc-root created

$ oc apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-root
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc-root
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-efs-claim-root
spec:
  containers:
    - name: httpd
      image: quay.io/fedora/fedora:43
      volumeMounts:
        - mountPath: /mnt/storage
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: efs-claim-root
EOF
persistentvolumeclaim/efs-claim-root created
pod/pod-with-efs-claim-root created

$ oc apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-root-b
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc-root
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-efs-claim-root-b
spec:
  containers:
    - name: httpd
      image: quay.io/fedora/fedora:43
      volumeMounts:
        - mountPath: /mnt/storage
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: efs-claim-root-b
EOF
persistentvolumeclaim/efs-claim-root-b created
pod/pod-with-efs-claim-root-b created

# STEP2: create efs-root-explorer pod to check the root directory data
$ oc apply -f - <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-root-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04a5e85869452b2fa 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-root-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-root-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-root-explorer
spec:
  containers:
  - name: explorer
    image: quay.io/fedora/fedora:43
    command: [ "sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: efs-root
      mountPath: /mnt/efs
  volumes:
  - name: efs-root
    persistentVolumeClaim:
      claimName: efs-root-pv-claim
EOF  
 persistentvolume/efs-root-pv created
persistentvolumeclaim/efs-root-pv-claim created
pod/efs-root-explorer created

$ oc rsh efs-root-explorer
sh-5.1# cd /mnt/efs/
sh-5.1# ls
pvc-02913afb-ce79-4f65-bfe3-8593390efad0  pvc-c86fcd50-5aec-4cd8-b298-bf6612b58608
sh-5.1#


# STEP3: create root-directory Path=/ accesspoint and static pv with this accesspoint, also create pvc and pod consume the volume
$ aws efs create-access-point \
  --file-system-id fs-04a5e85869452b2fa \
  --root-directory Path=/,CreationInfo="{OwnerUid=0,OwnerGid=0,Permissions=700}"

{
    "ClientToken": "XXXXXX",
    "Tags": [],
    "AccessPointId": "fsap-036f9897e23598d89",
    "AccessPointArn": "arn:aws:elasticfilesystem:us-east-2: XXXXXX:access-point/fsap-036f9897e23598d89",
    "FileSystemId": "fs-04a5e85869452b2fa",
    "RootDirectory": {
        "Path": "/",
        "CreationInfo": {
            "OwnerUid": 0,
            "OwnerGid": 0,
            "Permissions": "700"
        }
    },
    "OwnerId": "XXXXXX",
    "LifeCycleState": "creating"
}

$ oc apply -f - <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-root-pv-new
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1756815198315-8315-efs.csi.aws.com
    volumeHandle: fs-04a5e85869452b2fa::fsap-036f9897e23598d89
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-root-pv-new-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-root-pv-new
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-root-explorer-new
spec:
  containers:
  - name: explorer
    image: quay.io/fedora/fedora:43
    command: [ "sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: efs-root
      mountPath: /mnt/efs
  volumes:
  - name: efs-root
    persistentVolumeClaim:
      claimName: efs-root-pv-new-claim
EOF
persistentvolume/efs-root-pv-new created
persistentvolumeclaim/efs-root-pv-new-claim created
pod/efs-root-explorer-new created

$ oc rsh efs-root-explorer-new
sh-5.1# cd /mnt/efs/
sh-5.1# echo $HOSTNAME > testfile
sh-5.1# ls
pvc-02913afb-ce79-4f65-bfe3-8593390efad0  pvc-c86fcd50-5aec-4cd8-b298-bf6612b58608  testfile


# STEP4: Delete the efs-root-explorer-new pod and efs-root-pv-new-claim pvc trigger the delete root directory, the issue is still reproduced
# the other 2 pvcs directory deleted as unexpected and we could see their accesspoints still exist
$ oc delete po/efs-root-explorer-new pvc/efs-root-pv-new-claim
pod "efs-root-explorer-new" deleted
persistentvolumeclaim "efs-root-pv-new-claim" deleted

$ oc rsh efs-root-explorer
sh-5.1# cd /mnt/efs/
sh-5.1# ls
sh-5.1#

$ oc describe pv efs-root-pv-new
...
Events:
  Type     Reason              Age                  From                                                                Message
  ----     ------              ----                 ----                                                                -------
  Warning  VolumeFailedDelete  110s (x13 over 20m)  efs.csi.aws.com_ip-10-0-53-70_6d7acd86-3697-4afe-a7eb-4241edcbe3a0  rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy

$ aws efs describe-access-points \
  --file-system-id fs-04a5e85869452b2fa\
  --query "AccessPoints[*].[AccessPointId,LifeCycleState]" \
  --output table
-----------------------------------------
|         DescribeAccessPoints          |
+-------------------------+-------------+
|  fsap-07df8e7391b269a2a |  available  |
|  fsap-0042cc4053ece4625 |  available  |
|  fsap-0a6644842fabf2fbc |  available  |
|  fsap-036f9897e23598d89 |  available  |
+-------------------------+-------------+ 
```
with the reproducer I could still reproduce the issue even on driver version `v2.1.8`, so does it mean my reproducer is another separate potential bug?
I could see in controller logs delete access point root directory failed while actually all root directory data deleted.
```console
$ kubectl logs -l app=aws-efs-csi-driver-controller -c csi-driver --tail=100|grep 'fsap-048248543b0ece018'

I0903 12:47:28.562799       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:47:28.624120       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:47:28.925227       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:47:29.926303       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:47:29.983668       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:47:30.084577       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:47:32.086262       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:47:32.144711       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:47:32.241456       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:47:36.243704       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:47:36.290506       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:47:36.383158       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:47:44.384670       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:47:44.427622       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:47:44.529444       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:48:00.530669       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:48:00.583027       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:48:00.681299       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:48:32.682360       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:48:32.732691       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:48:32.832601       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:49:36.833664       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:49:36.904753       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:49:37.003898       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:51:45.005752       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:51:45.066934       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:51:45.161774       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:56:01.162980       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:56:01.231503       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:56:01.327158       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 12:58:46.157355       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 12:58:46.213362       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 12:58:46.311228       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 13:01:01.328905       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 13:01:01.451386       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 13:01:01.575984       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 13:06:01.577363       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 13:06:01.753133       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 13:06:01.854803       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 13:11:01.856091       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 13:11:02.027019       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 13:11:02.127033       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 13:13:46.158254       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 13:13:46.205258       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 13:13:46.310138       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 13:16:02.128363       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 13:16:02.353792       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 13:16:02.452389       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 13:21:02.453939       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 13:21:02.560119       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 13:21:02.658561       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
I0903 13:26:02.660067       1 controller.go:396] DeleteVolume: called with args {VolumeId:fs-0c64a49a5d65b7fd3::fsap-048248543b0ece018 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0903 13:26:02.755809       1 mount_linux.go:218] Mounting cmd (mount) with arguments (-t efs -o tls,iam fs-0c64a49a5d65b7fd3 /var/lib/csi/pv/fsap-048248543b0ece018)
E0903 13:26:02.853616       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not delete access point root directory "/": unlinkat /var/lib/csi/pv/fsap-048248543b0ece018: device or resource busy
```
