### ISSUE TITLE
[helm v3.1.3] exec /bin/aws-efs-csi-driver: exec format error

### ISSUE THREAD

**Issue by QuentinBtd** [kubernetes-sigs/aws-efs-csi-driver#1544]
/kind bug

**What happened?**

Running ARM64 image on ARM64 node, the exec format of application is bad
`public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver:v2.1.2`

`exec /bin/aws-efs-csi-driver: exec format error`

**How to reproduce it (as minimally and precisely as possible)?**

Adding a graviton instance node to the cluster. 

**Anything else we need to know?**:

Tested two times on two differents clusters

**Environment**
- Kubernetes version (use `kubectl version`): v1.31.2-eks-7f9249a
- Driver version: v2.1.2

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by peterabarr** [comment]
Seeing the same behavior

**Comment by jrakas-dev** [comment]
Thanks so much for bringing this up! We just pushed a new multi-architecture image that has arm64 support. Please try pulling in the new image and trying again. 
```
docker pull public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver:v2.1.2
```
As always, let us know if you encounter any other issues.

**Comment by QuentinBtd** [comment]
It works well now!

Thank you 😄

**Comment by kkopachev** [comment]
@jrakas-dev 
`602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/aws-efs-csi-driver:v2.1.2` still amd64 only

**Comment by minosmlee** [comment]
@jrakas-dev 
`602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/aws-efs-csi-driver:v2.1.2` also still amd64 only.

**Comment by nicolascollet-aldebarancom** [comment]
@jrakas-dev 
Same problem, AWS ECS internal registries  are not updated. So problem still here.

I thought it was not a good practice to push changes to the same tag?
The usage is to use **imagePullPolicy:  IfNotPresent**, so the problem will persist as long as the node (or proxy) has the image in cache.

Following Semantic Versioning, this amounts to a PATCH
so a version v2.1.3?
No ?

**Comment by diranged** [comment]
This warrants a re-release of the images with a new version IMO

**Comment by natechensan** [comment]
+1 for a patch version

**Comment by jrakas-dev** [comment]
Thanks for bringing this up. We're in the process of releasing v2.1.3 which has both arm and amd images. It is already available publicly and in `602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/aws-efs-csi-driver:v2.1.3`, and should be available as an EKS add-on by the end of the week.

**Comment by andrewbeard** [comment]
> Thanks for bringing this up. We're in the process of releasing v2.1.3 which has both arm and amd images. It is already available publicly and in the `602401143452` repository under `aws-efs-csi-driver:v2.1.3`, and should be available as an EKS add-on by the end of the week.

In the mean time anyone using the EKS add-on with an ARM worker node is dead in the water. We have a support case open but the rep does not seem to understand we can’t just tell an EKS addon to use another repository. Please do whatever you can to expedite releasing 2.1.3, uploading ARM 2.1.2 images, or rolling back to 2.1.1.

**Comment by jrakas-dev** [comment]
I understand the frustration -- EKS add-ons take time and the release timelines are outside of our control. As a workaround, you are welcome to manually edit the daemonset and deployment using the kubernetes API directly to change the efs-csi-driver image to point to a different tag.

Apply change to controller:
```
kubectl edit deployment efs-csi-controller -n kube-system
```
Save:
```
kubectl rollout status deployment efs-csi-controller -n kube-system
```
Verify:
```
kubectl describe deployment efs-csi-controller -n kube-system | grep Image
```
Apply change to daemonset:
```
kubectl edit daemonset efs-csi-node -n kube-system
```
Verify:
```
kubectl describe daemonset efs-csi-node -n kube-system | grep Image
```

Please note that this is a temporary workaround, and once `v2.1.3` is released to add-ons, you should run the following so that AWS can override your manual changes and regain control of updates 
```
aws eks update-addon \
  --cluster-name <your-cluster-name> \
  --addon-name efs-csi-driver \
  --resolve-conflicts OVERWRITE
```

**Comment by andrewbeard** [comment]
> Thanks for bringing this up. We're in the process of releasing v2.1.3 which has both arm and amd images. It is already available publicly and in the `602401143452` repository under `aws-efs-csi-driver:v2.1.3`, and should be available as an EKS add-on by the end of the week.

The commands above to patch the cluster were useful, thank you. The EKS add-on release does not seem to have occurred yet, though. Any update on the timeline for availability of 2.1.3?
